version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    user: postgres
    environment:
      POSTGRES_PASSWORD: "heimdall123"
      POSTGRES_DB: "testedb"
    ports:
      - "5432:5432"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - heimdall

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - heimdall
    depends_on:
      - postgres

networks: 
  heimdall:
    driver: bridge